apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml3-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml3-app
  template:
    metadata:
      labels:
        app: ml3-app
    spec:
      containers:
      - name: ml3-app-container
        image: your-dockerhub-username/ml3-app:latest
        ports:
        - containerPort: 8501
